remote_theme: pmarsceill/just-the-docs
logo: "/assets/images/help.png"
aux_links:
  "Home":
    - "//coronawhatnow.com"
  "Help Us":
    - "//www.facebook.com/groups/coronawhatnow/edit"
  "GitHub":
    - "//github.com/coronawhatnow/coronawhatnow.com"
