remote_theme: pmarsceill/just-the-docs
aux_links:
  "Home":
    - "//www.coronawhatnow.com"
  "Help Us":
    - "//www.facebook.com/groups/coronawhatnow/edit"
  "GitHub":
    - "//github.com/coronawhatnow/coronawhatnow.com"
